## Lab 4 (ML)
### Name: Smit Khobragade
### Roll no.: 64
### Sec: A


###K-NN FOR REGRESSION.[PR NO. 4]

#### PART A
- length = [10.0, 11.0, 12.0, 7.0, 9.0, 8.0,6.0,15.0,14.0,7.0,10.0,13.0,9.0,5.0,5.0]
- weight = [15.0, 6.0 , 14.0 , 9.0 ,14.0,12.0,11.0,10.0,8.0,12.0,6.0,8.0,7.0,8.0,10.0]
- cost = [45,37,48,33,38,40,35,50,46,35,36,44,32,30,30]
- k = 9
- predict for length = 7, height = 8

In [ ]:
length = [10.0, 11.0, 12.0, 7.0, 9.0, 8.0, 6.0, 15.0, 14.0, 7.0, 10.0, 13.0, 9.0, 5.0, 5.0]
weight = [15.0, 6.0, 14.0, 9.0, 14.0, 12.0, 11.0, 10.0, 8.0, 12.0, 6.0, 8.0, 7.0, 8.0, 10.0]
cost = [45, 37, 48, 33, 38, 40, 35, 50, 46, 35, 36, 44, 32, 30, 30]

data = list(zip(length, weight, cost))
data

[(10.0, 15.0, 45),
 (11.0, 6.0, 37),
 (12.0, 14.0, 48),
 (7.0, 9.0, 33),
 (9.0, 14.0, 38),
 (8.0, 12.0, 40),
 (6.0, 11.0, 35),
 (15.0, 10.0, 50),
 (14.0, 8.0, 46),
 (7.0, 12.0, 35),
 (10.0, 6.0, 36),
 (13.0, 8.0, 44),
 (9.0, 7.0, 32),
 (5.0, 8.0, 30),
 (5.0, 10.0, 30)]

In [ ]:
new_point = (7, 8)
k = 9

In [ ]:
def euclidean_distance(point1, point2):
  return ((point1[0] - point2[0])**2 + (point1[1] - point2[1])**2) ** 0.5

In [ ]:

def predict_cost(data, new_point, k):
    distances = []
    for point in data:
        features = point[:2]
        cost = point[2]
        distance = euclidean_distance(features, new_point)
        distances.append((distance, cost))

    distances.sort(key=lambda x: x[0])
    k_nearest = distances[:k]

    avg_cost = sum(cost for _, cost in k_nearest) / k #AVG of k nearest points

    return avg_cost

In [ ]:
final = predict_cost(data, new_point, k)
print(f'Predicted cost for (length=7, weight=8): {final:.2f}')

Predicted cost for (length=7, weight=8): 34.22


#### PART B
##### Operate on IRIS Dataset

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
import numpy as np

In [ ]:
data = pd.read_csv('/content/Iris.csv')
data

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [ ]:
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
iris = load_iris()
X = iris.data
y = iris.target
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=42)

In [ ]:
k = 3
knn = KNeighborsClassifier(n_neighbors=k)
knn.fit(X_train, y_train)

KNeighborsClassifier(n_neighbors=3)

In [ ]:
y_pred = knn.predict(X_test)

In [ ]:
conf_matrix = confusion_matrix(y_test, y_pred)
report = classification_report(y_test, y_pred, target_names=iris.target_names)

In [ ]:
report

'              precision    recall  f1-score   support\n\n      setosa       1.00      1.00      1.00        19\n  versicolor       1.00      1.00      1.00        13\n   virginica       1.00      1.00      1.00        13\n\n    accuracy                           1.00        45\n   macro avg       1.00      1.00      1.00        45\nweighted avg       1.00      1.00      1.00        45\n'

In [ ]:
print('Confusion Matrix:')
print(conf_matrix)
print('\nClassification Report:')
print(report)

Confusion Matrix:
[[19  0  0]
 [ 0 13  0]
 [ 0  0 13]]

Classification Report:
              precision    recall  f1-score   support

      setosa       1.00      1.00      1.00        19
  versicolor       1.00      1.00      1.00        13
   virginica       1.00      1.00      1.00        13

    accuracy                           1.00        45
   macro avg       1.00      1.00      1.00        45
weighted avg       1.00      1.00      1.00        45



In [ ]:
def predict_sample(sample):
    sample = [sample]
    prediction = knn.predict(sample)
    class_name = iris.target_names[prediction[0]]
    return class_name

sample_point = [5.1, 3.5, 1.4, 0.2]
predicted_class = predict_sample(sample_point)
print(f'\nPredicted class for sample point {sample_point}: {predicted_class}')


Predicted class for sample point [5.9, 3.0, 5.1, 1.8]: virginica
